name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: problems.tex
          compiler: pdflatex
      - name: Compile LaTeX document #2
        uses: dante-ev/latex-action@latest
        with:
          root_file: problems.tex
          compiler: pdflatex
      - name: Compile LaTeX document #3
        uses: dante-ev/latex-action@latest
        with:
          root_file: problems.tex
          compiler: pdflatex
      - name: create directory
        shell: bash
        run: mkdir dist && mkdir dist/${{ steps.extract_branch.outputs.branch }} && cp problems.pdf dist/${{ steps.extract_branch.outputs.branch }}
#      - name: create list of questions latex document
#        shell: bash
#        run: cd exam && python3 generate_list.py
#      - name: create document with questions
#        uses: dante-ev/latex-action@latest
#        with:
#          root_file: exam/exam_document.tex
#          compiler: pdflatex
#      - name: create list of questions latex document
#        shell: bash
#        run: ls -la 
#      - name: copy questions
#        shell: bash
#        run: cp exam_document.pdf dist/${{ steps.extract_branch.outputs.branch }}
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: pages
          token: ${{ secrets.ACCESS_TOKEN }}
          
